// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqs8cy_w9YLHXalt03HmSvvAMOBnGYPAs',
    appId: '1:224676894553:web:a71e483156ce9ad0569e48',
    messagingSenderId: '224676894553',
    projectId: 'mint-i',
    authDomain: 'mint-i.firebaseapp.com',
    storageBucket: 'mint-i.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCidJ5GMrCnvgRq9n_WNcc2YK5X0n404zI',
    appId: '1:224676894553:android:9623cffba3f2df65569e48',
    messagingSenderId: '224676894553',
    projectId: 'mint-i',
    storageBucket: 'mint-i.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBE8buE6jLLfZzHkapFnr87Oiy4OdRQfoY',
    appId: '1:224676894553:ios:3dd8c83926b3e6d4569e48',
    messagingSenderId: '224676894553',
    projectId: 'mint-i',
    storageBucket: 'mint-i.appspot.com',
    iosBundleId: 'com.example.e3ada4',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBE8buE6jLLfZzHkapFnr87Oiy4OdRQfoY',
    appId: '1:224676894553:ios:3dd8c83926b3e6d4569e48',
    messagingSenderId: '224676894553',
    projectId: 'mint-i',
    storageBucket: 'mint-i.appspot.com',
    iosBundleId: 'com.example.e3ada4',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCqs8cy_w9YLHXalt03HmSvvAMOBnGYPAs',
    appId: '1:224676894553:web:9b17e759b601dda5569e48',
    messagingSenderId: '224676894553',
    projectId: 'mint-i',
    authDomain: 'mint-i.firebaseapp.com',
    storageBucket: 'mint-i.appspot.com',
  );
}
